# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c48c85991d70e446545f63bad03d69222cfbdf346b559e2141e664fa177ba97cf48e74065f54a5cf84035401ad1213e432fd6b8bee9b57c633f0d504d5a48868

test:
  secret_key_base: fc73767a8f9ac273e33838f636333c2f8e3f7b7fbbfcd2590b92f6c914d30db90350e0fabd9ad9915920fd17e0a93a46ea2be3bc59792f33485e8ce4a41c071b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
